### ISSUE TITLE
When my Kingdom is less than 310 days old.

### ISSUE THREAD

**Issue by nyadolan** [sho-87/rok-talents-issues#14]
commanders of 310 days in ossiris Is it available? When my Kingdom is less than 310 days old.

**Comment by nyadolan** [comment]
> commanders of 310 days in ossiris Is it available?

When my Kingdom is less than 310 days old.

**Comment by sho-87** [comment]
I believe we're only up to 240 day commanders right now (e.g. Attila, Takeda, Guan Yu), and theyre usable in ark of osiris

After Artemisia and Ramesses, I think the next 2 will be 360 day commanders, but they are not released yet

**Comment by sho-87** [comment]
Just saw the latest update about 310 commanders. Theyve all been usable in osiris so far, not sure about osiris league
